### ISSUE TITLE
Dictionaries 

### ISSUE THREAD

**Issue by prmiller91** [chapinb/anparser#2]
In each plugin script, data is added to a dictionary before being added to a list which is then sent to a writer for CSV conversion. The problem, is that dictionaries are unordered, so what you add to the dictionary isn't necessarily the order it will be in the CSV. This might cause problems later on when you want to dictate how the data is shown in the CSV. Do you think one singular list might be better and just specify the headers in a separate list? The image below is an ouput illustrating my issue -  Table, _id, title, url, etc. are entered in the dictionary, but it comes out in a different order in the CSV.
![screen shot 2015-01-07 at 8 38 31 pm](https://cloud.githubusercontent.com/assets/9575133/5657064/54d1d6d8-96ad-11e4-8831-12be40fe83f6.png)

**Comment by chapinb** [comment]
I noticed this issue as well in the plugins I had written thus far. I want to test and see if the order they are assigned plays a role in the order in which they are written or if some other sorting method should take place prior to that.

Overall I prefer to use the dictionary format as it keeps the data nice and organized at all times (since a lot of data is floating around within the script). I felt the redundancy while writing, though wonder if there is a more efficient manner to structure the data. 

Thoughts?

This could also raise issues when writing to other formats, such as XLSX, XML, SQL, etc. in the future.

**Comment by prmiller91** [comment]
OrderedDict from the collections module was the solution to this problem. Fixed #2

**Comment by chapinb** [comment]
Corrected in 41d405c6303f9d5a6d7e18922a1868606ee8698f
